apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: demo-namespace
data:
  REDIS_PASSWORD: wesang
  redis-config: |
    maxmemory 100mb
    maxmemory-policy allkeys-lru
    protected-mode no
    requirepass wesang
