apiVersion: v1
kind: Service
metadata:
  name: pubsub-svc
  namespace: demo-namespace
spec:
  type: LoadBalancer
  selector:
    app: pubsub-emulators
  ports:
  - protocol: TCP
    port: 6066
    targetPort: 6066
    nodePort: 30066
---
apiVersion: v1
kind: Service
metadata:
  name: datastore-svc
  namespace: demo-namespace
spec:
  type: LoadBalancer
  selector:
    app: datastore-emulators
  ports:
  - protocol: TCP
    port: 6067
    targetPort: 6067
    nodePort: 30067
---
apiVersion: v1
kind: Service
metadata:
  name: storage-svc
  namespace: demo-namespace
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: storage-emulators
  ports:
  - protocol: TCP
    port: 9023
    targetPort: 9023
    nodePort: 30923
