apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-pv
  namespace: demo-namespace
  labels:
    type: local
    app: postgresdb
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  # A db can write and read from volumes to multiple pods
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/var/lib/postgresql/data"
