apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-pvc
  namespace: demo-namespace
  labels:
    type: local
    app: postgresdb
spec:
  storageClassName: manual
  accessModes:
  # Allow ReadWrite to multiple pods
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
