apiVersion: v1
kind: Service
metadata:
  name: postgresdb-svc
  namespace: demo-namespace
  labels:
    app: postgresdb
spec:
  type: NodePort
  selector:
    app: postgresdb
  ports:
  - port: 5432
    name: postgresdb
    protocol: TCP
    targetPort: 5432
    nodePort: 30432
