apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: demo-namespace
  labels:
    app: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - protocol: TCP
    name: redis
    port: 6379
    targetPort: 6379
    nodePort: 30379
