apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  namespace: demo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres:16-alpine
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data
        envFrom:
          - secretRef:
              name: demo-secrets
        volumeMounts:
          - name: postgresdata
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgresdb-pvc
